#!/bin/sh

# 1. Configure Underlay IP on eth0
ip addr add 10.1.1.2/24 dev eth0
ip link set eth0 up

# 2. Create and enable Linux Bridge
ip link add br0 type bridge
ip link set br0 up

# 3. Create VXLAN interface (VNI 10, Multicast Group 239.1.1.1)
ip link add vxlan10 type vxlan id 10 dev eth0 group 239.1.1.1 dstport 4789
ip link set vxlan10 up

# 4. Attach eth1 (Host interface) and vxlan10 to bridge br0
ip link set eth1 master br0
ip link set eth1 up
ip link set vxlan10 master br0