#!/bin/sh

# 1. Setup Underlay IP interface
ip addr add 10.1.1.1/24 dev eth0
ip link set eth0 up

# 2. Create and activate Linux Bridge
ip link add br0 type bridge
ip link set br0 up

# 3. Create VXLAN 10 interface in Static Unicast Mode (pointing directly to Router 2: 10.1.1.2)
ip link add vxlan10 type vxlan id 10 dev eth0 remote 10.1.1.2 dstport 4789
ip link set vxlan10 up

# 4. Attach eth1 (Host interface) and vxlan10 to bridge br0
ip link set eth1 master br0
ip link set eth1 up
ip link set vxlan10 master br0