#!/bin/sh

# Assign IPs to Interfaces
ip addr add 1.1.1.1/32 dev lo
ip addr add 10.1.1.1/30 dev eth0
ip addr add 10.1.1.5/30 dev eth1
ip addr add 10.1.1.9/30 dev eth2

# Configure OSPF inside FRRouting
vtysh -c "
configure terminal
router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.1.1.0/30 area 0
 network 10.1.1.4/30 area 0
 network 10.1.1.8/30 area 0
exit
"