#!/bin/sh

# 1. Enable & Assign IPs to Interfaces
ip link set eth0 up
ip link set eth1 up
ip link set eth2 up

ip addr add 1.1.1.1/32 dev lo
ip addr add 10.1.1.1/30 dev eth0
ip addr add 10.1.1.5/30 dev eth1
ip addr add 10.1.1.9/30 dev eth2

# 2. Configure OSPF & BGP EVPN (Route Reflector) inside FRRouting
vtysh -c "
configure terminal

router ospf
 ospf router-id 1.1.1.1
 network 1.1.1.1/32 area 0
 network 10.1.1.0/30 area 0
 network 10.1.1.4/30 area 0
 network 10.1.1.8/30 area 0
exit

router bgp 1
 bgp router-id 1.1.1.1
 neighbor 1.1.1.2 remote-as 1
 neighbor 1.1.1.2 update-source lo
 neighbor 1.1.1.3 remote-as 1
 neighbor 1.1.1.3 update-source lo
 neighbor 1.1.1.4 remote-as 1
 neighbor 1.1.1.4 update-source lo
 !
 address-family l2vpn evpn
  neighbor 1.1.1.2 activate
  neighbor 1.1.1.2 route-reflector-client
  neighbor 1.1.1.3 activate
  neighbor 1.1.1.3 route-reflector-client
  neighbor 1.1.1.4 activate
  neighbor 1.1.1.4 route-reflector-client
 exit-address-family
exit
"